# Created by Jekyll Writer
title: kikpin
author: kikpin
description: hello world !
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: kikpin
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''

# comments 评论功能
comments:
  gitalk: true
  gitalk_clientID: '6a87821d43a5c898715e'
  gitalk_Secret: 'be577df309ba61a7d0f3ee9d0379300a3f3079c7'
  gitalk_repo: 'kikpin.github.io'
  gitalk_owner: 'kikpin'
  gitalk_admin: 'kikpin'
  distractionFreeMode: true