# Created by Jekyll Writer
author: kikpin
description: hello world !
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: kikpin
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
title: kikpin
