# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.kikpin.com
date_format: "ordinal"
title: kikpin
subtitle: "blog.kikpin.com"
description: "blog.kikpin.com"
keywords: kikpin
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5
repository: kikpin/kikpin.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-04-01
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: kikpin
organization: 
organization_url: 
github_username: kikpin
location: Wuhan, China
email: kikpin@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 文档摘抄

#   -
#     href: /links/
#     label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: false
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: kikpin
    repo: kikpin.github.io
    oauth:
        client_id: 6a87821d43a5c898715e
        client_secret: be577df309ba61a7d0f3ee9d0379300a3f3079c7
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin
    repo: kikpin.github.io
    clientID: 6a87821d43a5c898715e
    clientSecret: be577df309ba61a7d0f3ee9d0379300a3f3079c7
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: ''
    adsense:
        footer: false
        sidebar: false 
        content_header: false
        content_footer: false